[metadata]
creation_date = "2026/03/22"
integration = ["endpoint"]
maturity = "production"
updated_date = "2026/03/22"

[rule]
author = ["Elastic"]
description = "Test rule for PoC"
name = "PoC Test Rule"
risk_score = 21
severity = "low"
type = "query"
query = '''process.name : "test"'''

[[rule.threat]]
framework = "MITRE ATT&CK"

[rule.threat.tactic]
id = "TA0001"
name = "Initial Access"
reference = "https://attack.mitre.org/tactics/TA0001/"
