# Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
# or more contributor license agreements. Licensed under the Elastic License
# 2.0; you may not use this file except in compliance with the Elastic License
# 2.0.

"""Type stubs for the python-esql package (which ships without a py.typed marker).

Covers the public API surface used by detection-rules; extend as new
python-esql helpers are adopted.
"""

from types import TracebackType
from typing import Any

from semver import Version

from . import ast as ast

__version__: str
__es_compat__: str

class EsqlError(Exception): ...
class EsqlSyntaxError(EsqlError): ...
class EsqlSemanticError(EsqlError): ...
class EsqlSchemaError(EsqlSemanticError): ...
class EsqlTypeMismatchError(EsqlSemanticError): ...
class EsqlUnsupportedTypeError(EsqlSemanticError): ...
class EsqlVersionError(EsqlSemanticError): ...
class EsqlNestedQueryError(EsqlSemanticError): ...

class ParserConfig:
    """Context manager for parser / validator configuration."""

    def __init__(self, *managers: ParserConfig, **config: Any) -> None: ...
    @classmethod
    def read_stack(cls, name: str, default: Any = None, silent: bool = True) -> Any: ...
    def __enter__(self) -> ParserConfig: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

class Schema(ParserConfig):
    """Field schema for semantic validation."""

    allow_missing: bool
    index_pattern: str | None
    def __init__(
        self,
        mapping: dict[str, Any],
        *,
        allow_missing: bool = False,
        index_pattern: str | None = None,
    ) -> None: ...
    def resolve_field(self, name: str) -> str | None: ...

class EventDataset:
    package: str
    integration: str
    def __init__(self, package: str, integration: str) -> None: ...

def parse_query(text: str) -> ast.EsqlQuery: ...
def parse_expression(text: str) -> ast.Expression: ...
def render(tree: ast.EsqlQuery) -> str: ...
def validate_nested_queries(tree: ast.EsqlQuery) -> None: ...
def analyze(tree: ast.EsqlQuery, schema: Schema) -> None: ...
def infer_column_types(tree: ast.EsqlQuery, schema: Schema) -> dict[str, str]: ...
def verify_features(tree: ast.EsqlQuery, min_stack_version: str | Version | None = None) -> None: ...
def validate_detection_rule_query(tree: ast.EsqlQuery, name: str = "") -> None: ...
def get_from_sources(tree: ast.EsqlQuery) -> list[str]: ...
def get_metadata_fields(tree: ast.EsqlQuery) -> list[str]: ...
def get_field_names(tree: ast.EsqlQuery, *, include_output: bool = True) -> list[str]: ...
def get_unique_fields(tree: ast.EsqlQuery) -> list[str]: ...
def get_keep_columns(tree: ast.EsqlQuery) -> list[str]: ...
def get_stats_grouping_fields(tree: ast.EsqlQuery) -> list[str]: ...
def get_defined_columns(tree: ast.EsqlQuery) -> set[str]: ...
def is_aggregate_query(tree: ast.EsqlQuery) -> bool: ...
def has_keep(tree: ast.EsqlQuery) -> bool: ...
def get_datasets_and_modules(tree: ast.EsqlQuery) -> tuple[set[str], set[str]]: ...
def get_event_datasets(tree: ast.EsqlQuery) -> list[EventDataset]: ...
def find_nested_queries(tree: ast.EsqlQuery) -> list[ast.NestedQuery]: ...
