# Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
# or more contributor license agreements. Licensed under the Elastic License
# 2.0; you may not use this file except in compliance with the Elastic License
# 2.0.

"""Type stubs for the python-esql AST module."""

class BaseNode: ...
class Expression(BaseNode): ...
class NestedQuery(Expression): ...
class Command(BaseNode): ...
class EsqlQuery(BaseNode): ...
