name: docs-build
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
permissions:
  contents: read
  pull-requests: read
jobs:
  build:
    uses: elastic/docs-actions/.github/workflows/docs-build.yml@8f286cdc29e227d29b0f2ce7de232dc4412bad97 # v1
