name: docs-deploy
on:
  workflow_run:
    workflows: [docs-build]
    types: [completed]
permissions:
  contents: read
  deployments: write
  id-token: write
  pull-requests: write
  actions: read
jobs:
  deploy:
    uses: elastic/docs-actions/.github/workflows/docs-deploy.yml@8f286cdc29e227d29b0f2ce7de232dc4412bad97 # v1
