name: docs-deploy
on:
  workflow_run:
    workflows: [docs-build]
    types: [completed]
permissions:
  contents: read
  deployments: write
  id-token: write
  pull-requests: write
  actions: read
jobs:
  deploy:
    uses: elastic/docs-actions/.github/workflows/docs-deploy.yml@6424787358d5b21453778294bfc93f97e3a0ae2f # v1
