name: docs-preview-cleanup
on:
  pull_request_target:
    branches: [main]
    types: [closed]
permissions:
  contents: none
  deployments: write
  id-token: write
jobs:
  cleanup:
    uses: elastic/docs-actions/.github/workflows/docs-preview-cleanup.yml@eba23ec1a23c6935cfb719ee35a080cc7985abaa # v1
