name: docs-build
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  merge_group:
    branches: [main]
permissions:
  contents: read
  pull-requests: read
jobs:
  build:
    uses: elastic/docs-actions/.github/workflows/docs-build.yml@d81f6d1ca859405eda61e5e376a1b37e00e44b44 # v1
